version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@1.0.0

jobs:
  # Cypress Running in Docker Example
  test-cypress-docker:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Cypress tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/cypress.yml
          testing-environment: docker
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  test-cypress:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Prepare Cypress Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/cypress.yml
          testing-environment: sauce
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Playwright Example
  test-playwright:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Playwright Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/playwright.yml
          testing-environment: docker
          environment:
            SKIP_CI: true
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Puppeteer Example
  test-puppeteer:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Puppeteer Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/puppeteer.yml
          testing-environment: docker
          environment:
            SKIP_CI: true
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Testcafe Example
  test-testcafe:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Prepare Testcafe Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/testcafe.yml
          testing-environment: docker
          environment:
            SKIP_CI: true
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-cypress-docker
      - test-cypress
      - test-playwright
      - test-puppeteer
      - test-testcafe
