version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@1.0.0

jobs:
  # Cypress Running in Docker Example
  test-cypress-docker:
    docker:
      - image: circleci/node:12.21
    environment:
      BUILD_ID: $CIRCLE_BUILD_NUM
      BUILD_ENV: CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Cypress tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/cypress.yml
          testing-environment: docker

  test-cypress:
    docker:
      - image: circleci/node:12.21
    environment:
      BUILD_ID: $CIRCLE_BUILD_NUM
      BUILD_ENV: CircleCI
    steps:
      - checkout
      - run:
          name: Prepare Cypress Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/cypress.yml
          testing-environment: sauce

  # Playwright Example
  test-playwright:
    docker:
      - image: circleci/node:12.21
    environment:
      BUILD_ID: $CIRCLE_BUILD_NUM
      BUILD_ENV: CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Playwright Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/playwright.yml
          testing-environment: docker

  # Puppeteer Example
  test-puppeteer:
    docker:
      - image: circleci/node:12.21
    environment:
      BUILD_ID: $CIRCLE_BUILD_NUM
      BUILD_ENV: CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Puppeteer Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/puppeteer.yml
          testing-environment: docker

  # Testcafe Example
  test-testcafe:
    docker:
      - image: circleci/node:12.21
    environment:
      BUILD_ID: $CIRCLE_BUILD_NUM
      BUILD_ENV: CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Testcafe Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
      - saucectl/saucectl-run:
          config-file: ./.sauce/testcafe.yml
          testing-environment: docker

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-cypress-docker
      - test-cypress
      - test-playwright
      - test-puppeteer
      - test-testcafe
