# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sauce Pipeline Browser Tests

on:
  pull_request:
  push:
    branches:
      - '*'

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCECTL_VERSION: 0.30.0

jobs:
  puppeteer:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Workaround for container permissions
        run: sudo chmod -R 777 tests/
      - uses: saucelabs/saucectl-run-action@v1
        with:
          saucectl-version: v${{ env.SAUCECTL_VERSION }}
          config-file: ./.sauce/puppeteer.yml
          testing-environment: docker
        env:
          SKIP_CI: true
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Workaround for container permissions
        run: sudo chmod -R 777 tests/
      - uses: saucelabs/saucectl-run-action@v1
        with:
          saucectl-version: v${{ env.SAUCECTL_VERSION }}
          config-file: ./.sauce/playwright.yml
          testing-environment: docker
        env:
          SKIP_CI: true
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  testcafe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Workaround for container permissions
        run: sudo chmod -R 777 tests/
      - uses: saucelabs/saucectl-run-action@v1
        with:
          saucectl-version: v${{ env.SAUCECTL_VERSION }}
          config-file: ./.sauce/testcafe.yml
          testing-environment: docker
        env:
          SKIP_CI: true
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Workaround for container permissions
        run: sudo chmod -R 777 tests/
      - uses: saucelabs/saucectl-run-action@v1
        with:
          saucectl-version: v${{ env.SAUCECTL_VERSION }}
          config-file: ./.sauce/cypress.yml
          testing-environment: docker
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
